from . import test_module
from . import test_all_templates

from . import test_agrosourcing
from . import test_brasserie_teddy_bear
from . import test_cafes_dagobert
from . import test_cds
from . import test_comptoir_des_lys
from . import test_coop_de_yenne
from . import test_croc_jbg_sas
from . import test_ecodis
from . import test_ekibio
from . import test_ferme_bio_margerie
from . import test_ferme_des_grands_noyers
from . import test_gonuts
from . import test_gravier
from . import test_helpac
from . import test_herbiolys
from . import test_markal
from . import test_papilles_sauvages
from . import test_relais_local
from . import test_relais_vert
from . import test_saldac
from . import test_scop_epice
from . import test_senfas
from . import test_supersec
from . import test_t_air_de_famille
from . import test_vitafrais
